export const TEAMS = [
  // Premier League
  'Arsenal',
  'Aston Villa',
  'Bournemouth',
  'Brentford',
  'Brighton & Hove Albion',
  'Chelsea',
  'Crystal Palace',
  'Everton',
  'Fulham',
  'Ipswich Town',
  'Leicester City',
  'Liverpool',
  'Man City',
  'Man United',
  'Newcastle',
  'Nottingham Forest',
  'Southampton',
  'Tottenham',
  'West Ham',
  'Wolverhampton',
  // La Liga
  'Atlético Madrid',
  'Barcelona',
  'Celta Vigo',
  'Eibar',
  'Espanyol',
  'Getafe',
  'Girona',
  'Granada',
  'Las Palmas',
  'Mallorca',
  'Osasuna',
  'Rayo Vallecano',
  'Real Betis',
  'Real Madrid',
  'Real Sociedad',
  'Sevilla',
  'Villarreal',
  'Alavés',
  'Cádiz',
  'Almería',
  // Serie A
  'AC Milan',
  'AS Roma',
  'Atalanta',
  'Bologna',
  'Cagliari',
  'Como',
  'Cremonese',
  'Empoli',
  'Fiorentina',
  'Frosinone',
  'Genoa',
  'Hellas Verona',
  'Inter Milan',
  'Juventus',
  'Lazio',
  'Lecce',
  'Monza',
  'Napoli',
  'Parma',
  'Sassuolo',
  'Torino',
  'Udinese',
  'Venezia',
  // Bundesliga
  'Augsburg',
  'Bayer Leverkusen',
  'Bayern Munich',
  'Borussia Dortmund',
  'Borussia Mönchengladbach',
  'Cologne',
  'Eintracht Frankfurt',
  'FC Heidenheim',
  'Freiburg',
  'Hoffenheim',
  'Mainz 05',
  'RB Leipzig',
  'SC Freiburg',
  'Stuttgart',
  'TSG Hoffenheim',
  'Union Berlin',
  'Werder Bremen',
  'Wolfsburg',
  // Ligue 1
  'Amiens',
  'Angers',
  'AS Saint-Étienne',
  'Auxerre',
  'AJ Auxerre',
  'Brest',
  'Clermont Foot',
  'ESTAC Troyes',
  'Girondins de Bordeaux',
  'Lens',
  'Lille',
  'Lyon',
  'Marseille',
  'Monaco',
  'Montpellier',
  'Nantes',
  'Nice',
  'Paris Saint-Germain',
  'Rennes',
  'Strasbourg',
  'Toulouse',
  // Other Notable Teams
  'Ajax',
  'AZ Alkmaar',
  'Benfica',
  'Braga',
  'Celtic',
  'Dinamo Zagreb',
  'Feyenoord',
  'Galatasaray',
  'Porto',
  'PSV Eindhoven',
  'Rangers',
  'RB Salzburg',
  'Shakhtar Donetsk',
  'Sporting CP',
  // National Teams
  'Argentina',
  'Croatia',
  'Czechia',
  'Denmark',
  'England',
  'Finland',
  'France',
  'Germany',
  'Ghana',
  'Hungary',
  'Iceland',
  'Ireland',
  'Italy',
  'Mexico',
  'Morocco',
  'Netherlands',
  'Northern Ireland',
  'Norway',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Scotland',
  'Spain',
  'Sweden',
  'Ukraine',
  'United States',
  'Wales',
] as const;

export type TeamName = (typeof TEAMS)[number];

export const STAGE_LABELS: Record<string, string> = {
  R16: 'Round of 16',
  QF: 'Quarter-Finals',
  SF: 'Semi-Finals',
  F: 'Final',
};

export const TOURNAMENT_FORMATS = [
  { value: 'league', label: 'League', description: 'Round-robin format where every player plays each other' },
  { value: 'knockout', label: 'Knockout', description: 'Single-elimination bracket tournament' },
  { value: 'cup', label: 'Cup', description: 'Group stage followed by knockout rounds' },
] as const;

export const TOURNAMENT_STATUSES = {
  draft: { label: 'Draft', color: '#8E8E93' }, // Apple Gray
  active: { label: 'Active', color: '#0A84FF' }, // Apple Blue
  completed: { label: 'Completed', color: '#34C759' }, // Apple Green
} as const;

export const FORM_COLORS = {
  W: '#34C759', // Apple Green (Win)
  D: '#8E8E93', // Apple Gray (Draw)
  L: '#FF3B30', // Apple Red (Loss)
} as const;
